---
title: "Regression and Other Stories - Tidyverse Examples"
output: 
  github_document:
    toc: true
---

This repository contains [Tidyverse](https://www.tidyverse.org/) implementations
of examples from _Regression and Other Stories_ by
[Andrew Gelman](http://www.stat.columbia.edu/~gelman/),
[Jennifer Hill](https://steinhardt.nyu.edu/people/jennifer-hill), and
[Aki Vehtari](https://users.aalto.fi/~ave/) (2020).

* [Book website](http://www.stat.columbia.edu/~gelman/regression/)
* Original code provided with book
  * [Code website](https://avehtari.github.io/ROS-Examples/examples.html)
  * [GitHub repository](https://github.com/avehtari/ROS-Examples)
  
Tidyverse version by [Bill Behrman](https://datalab.stanford.edu/bill).

-------------

## Examples by chapters

### 1 Introduction
- [ElectionsEconomy/](ElectionsEconomy/)
    - [hibbs_tv.md](ElectionsEconomy/hibbs_tv.md) - Predicting presidential vote share from the economy
- [ElectricCompany/](ElectricCompany/)
    - [electric_tv.md](ElectricCompany/electric_tv.md) - Analysis of "Electric Company" data
- [Peacekeeping/](Peacekeeping/)
    - [peace_tv.md](Peacekeeping/peace_tv.md) - Outcomes after civil war in countries with and without United Nations peacekeeping
- [SimpleCausal/](SimpleCausal/)
    - [causal_tv.md](SimpleCausal/causal_tv.md) - Simple graphs illustrating regression for causal inference
- [Helicopters/](Helicopters/)
    - [helicopters_tv.md](Helicopters/helicopters_tv.md) - Example data file for helicopter flying time exercise

### 2  Data and measurement
- [HDI/](HDI/)
    - [hdi_tv.md](HDI/hdi_tv.md) - Human Development Index - Looking at data in different ways
- [Pew/](Pew/)
    - [pew_tv.md](Pew/pew_tv.md) - Miscellaneous analyses using raw Pew data
- [HealthExpenditure/](HealthExpenditure/)
    - [healthexpenditure_tv.md](HealthExpenditure/healthexpenditure_tv.md) - Discovery through graphs of data and models
- [Names/](Names/)
    - [lastletters_tv.md](Names/lastletters_tv.md) - Last letters - Distributions of last letters of names of American babies
- [Congress/](Congress/)
    - [congress_plots_tv.md](Congress/congress_plots_tv.md) - Predictive uncertainty for congressional elections
- [AgePeriodCohort/](AgePeriodCohort/)
    - [births_tv.md](AgePeriodCohort/births_tv.md) - Age adjustment

### 3  Some basic methods in mathematics and probability
- [Mile/](Mile/)
    - [mile_tv.md](Mile/mile_tv.md) - Trend of record times in the mile run
- [Metabolic/](Metabolic/)
    - [metabolic_tv.md](Metabolic/metabolic_tv.md) - How to interpret a power law or log-log regression
- [CentralLimitTheorem/](CentralLimitTheorem/)
    - [heightweight_tv.md](CentralLimitTheorem/heightweight_tv.md) - Illustrate central limit theorem and normal distribution
- [Stents/](Stents/)
    - [stents_tv.md](Stents/stents_tv.md) - Stents - comparing distributions

### 4  Generative models and statistical inference
- [Coverage/](Coverage/)
    - [coverage_tv.md](Coverage/coverage_tv.md) - Example of coverage
- [Death/](Death/)
    - [polls_tv.md](Death/polls_tv.md) - Proportion of American adults supporting the death penalty
- [Coop/](Coop/)
    - [riverbay_tv.md](Coop/riverbay_tv.md) - Example of hypothesis testing
- [Girls/](Girls/)

### 5  Simulation
- [ProbabilitySimulation/](ProbabilitySimulation/)
    - [probsim_tv.md](ProbabilitySimulation/probsim_tv.md) - Simulation of probability models
- [Earnings/](Earnings/)
    - [earnings_bootstrap_tv.md](Earnings/earnings_bootstrap_tv.md) - Bootstrapping to simulate the sampling distribution

### 6  Background on regression modeling
- [Simplest/](Simplest/)
    - [simplest_tv.md](Simplest/simplest_tv.md) - Linear regression with a single predictor
- [Earnings/](Earnings/)
    - [earnings_regression_tv.md](Earnings/earnings_regression_tv.md) - Predict respondents' yearly earnings using survey data from 1990
- [PearsonLee/](PearsonLee/)
    - [heights_tv.md](PearsonLee/heights_tv.md) - The heredity of height. Published in 1903 by Karl Pearson and Alice Lee.
- [FakeMidtermFinal/](FakeMidtermFinal/)
    - [simulation_tv.md](FakeMidtermFinal/simulation_tv.md) - Fake dataset of 1,000 students' scores on a midterm and final exam

### 7  Linear regression with a single predictor
- [ElectionsEconomy/](ElectionsEconomy/)
    - [hibbs_tv.md](ElectionsEconomy/hibbs_tv.md) - Predicting presidential vote share from the economy
    - [hibbs_coverage_tv.md](ElectionsEconomy/hibbs_coverage_tv.md) - Checking the coverage of intervals
- [Simplest/](Simplest/)
    - [simplest_tv.md](Simplest/simplest_tv.md) - Linear regression with a single predictor

### 8 Fitting regression models
- [ElectionsEconomy/](ElectionsEconomy/)
    - [hills_tv.md](ElectionsEconomy/hills_tv.md) - Present uncertainty in parameter estimates
    - [hibbs_tv.md](ElectionsEconomy/hibbs_tv.md) - Predicting presidential vote share from the economy
- [Influence/](Influence/)
    - [influence_tv.md](Influence/influence_tv.md) - Influence of individual points in a fitted regression

### 9 Prediction and Bayesian inference
- [ElectionsEconomy/](ElectionsEconomy/)
    - [hibbs_tv.md](ElectionsEconomy/hibbs_tv.md) - Predicting presidential vote share from the economy
    - [bayes_tv.md](ElectionsEconomy/bayes_tv.md) - Demonstration of Bayesian information aggregation
- [Earnings/](Earnings/)
    - [height_and_weight_tv.md](Earnings/height_and_weight_tv.md) - Predict weight
- [SexRatio/](SexRatio/)
    - [sexratio_tv.md](SexRatio/sexratio_tv.md) - Example where an informative prior makes a difference

### 10  Linear regression with multiple predictors
- [KidIQ/](KidIQ/)
    - [kidiq_tv.md](KidIQ/kidiq_tv.md) - Linear regression with multiple predictors
- [Earnings/](Earnings/)
    - [height_and_weight_tv.md](Earnings/height_and_weight_tv.md) - Predict weight
- [Congress/](Congress/)
    - [congress_tv.md](Congress/congress_tv.md) - Predictive uncertainty for congressional elections
- [NES/](NES/)
    - [nes_linear_tv.md](NES/nes_linear_tv.md) - Fitting the same regression to many datasets
- [Beauty/](Beauty/)
    - [beauty_tv.md](Beauty/beauty_tv.md) - Student evaluations of instructors’ beauty and teaching quality

### 11  Assumptions, diagnostics, and model evaluation
- [KidIQ/](KidIQ/)
    - [kidiq_tv.md](KidIQ/kidiq_tv.md) - Linear regression with multiple predictors
- [Residuals/](Residuals/)
    - [residuals_tv.md](Residuals/residuals_tv.md) - Plotting the data and fitted model
- [Introclass/](Introclass/)
    - [residual_plots_tv.md](Introclass/residual_plots_tv.md) - Plot residuals vs.\ predicted values, or residuals vs.\ observed values?
- [Newcomb/](Newcomb/)
    - [newcomb_tv.md](Newcomb/newcomb_tv.md) - Posterior predictive checking of Normal model for Newcomb's speed of light data
- [Unemployment/](Unemployment/)
    - [unemployment_tv.md](Unemployment/unemployment_tv.md) - Time series fit and posterior predictive model checking for unemployment series
- [Rsquared/](Rsquared/)
    - [rsquared_tv.md](Rsquared/rsquared_tv.md) - Bayesian R^2
- [CrossValidation/](CrossValidation/)
    - [crossvalidation_tv.md](CrossValidation/crossvalidation_tv.md) - Demonstration of cross validation
- [FakeKCV/](FakeKCV/)
    - [fake_kcv_tv.md](FakeKCV/fake_kcv_tv.md) - Demonstration of $K$-fold cross-validation using simulated data
- [Pyth/](Pyth/)

### 12  Transformations
- [KidIQ/](KidIQ/)
    - [kidiq_tv.md](KidIQ/kidiq_tv.md) - Linear regression with multiple predictors
- [Earnings/](Earnings/)
    - [earnings_regression_tv.md](Earnings/earnings_regression_tv.md) - Predict respondents' yearly earnings using survey data from 1990
- [Gay/](Gay/)
    - [gay_simple_tv.md](Gay/gay_simple_tv.md) - Simple models (linear and discretized age) and political attitudes as a function of age
- [Mesquite/](Mesquite/)
    - [mesquite_tv.md](Mesquite/mesquite_tv.md) - Predicting the yields of mesquite bushes
- [Student/](Student/)
    - [student_tv.md](Student/student_tv.md) - Models for regression coefficients
- [Pollution/](Pollution/)
    - [pollution_tv.md](Pollution/pollution_tv.md) - Pollution data

### 13  Logistic regression
- [NES/](NES/)
    - [nes_logistic_tv.md](NES/nes_logistic_tv.md) - Logistic regression, identifiability, and separation
- [LogisticPriors/](LogisticPriors/)
    - [logistic_priors_tv.md](LogisticPriors/logistic_priors_tv.md) - Effect of priors in logistic regression
- [Arsenic/](Arsenic/)
    - [arsenic_logistic_building_tv.md](Arsenic/arsenic_logistic_building_tv.md) - Building a logistic regression model: wells in Bangladesh
- [Rodents/](Rodents/)

### 14  Working with logistic regression
- [LogitGraphs/](LogitGraphs/)
    - [logitgraphs_tv.md](LogitGraphs/logitgraphs_tv.md) - Different ways of displaying logistic regression
- [Arsenic/](Arsenic/)
    - [arsenic_logistic_building_tv.md](Arsenic/arsenic_logistic_building_tv.md) - Building a logistic regression model: wells in Bangladesh
    - [arsenic_logistic_apc_tv.md](Arsenic/arsenic_logistic_apc_tv.md) - Average predictive comparisons for a logistic regression model: wells in Bangladesh
    - [arsenic_logistic_residuals_tv.md](Arsenic/arsenic_logistic_residuals_tv.md) - Residual plots for a logistic regression model: wells in Bangladesh
- [NES/](NES/)
    - [nes_logistic_tv.md](NES/nes_logistic_tv.md) - Logistic regression, identifiability, and separation

### 15  Other generalized linear models
- [PoissonExample/](PoissonExample/)
    - [poisson_regression_tv.md](PoissonExample/poisson_regression_tv.md) - Demonstrate Poisson regression with simulated data
- [Roaches/](Roaches/)
    - [roaches_tv.md](Roaches/roaches_tv.md) - Analyze the effect of integrated pest management on reducing cockroach levels in urban apartments
- [Storable/](Storable/)
    - [storable_tv.md](Storable/storable_tv.md) - Ordered categorical data analysis with a study from experimental economics, on the topic of "storable votes"
- [Robit/](Robit/)
    - [robit_tv.md](Robit/robit_tv.md) - Comparison of robit and logit models for binary data
- [Earnings/](Earnings/)
    - [earnings_compound_tv.md](Earnings/earnings_compound_tv.md) - Compound discrete-continuous model
- [RiskyBehavior/](RiskyBehavior/)
    - [risky_tv.md](RiskyBehavior/risky_tv.md) Risky behavior data
- [NES/](NES/)
- [Lalonde/](Lalonde/)
- [Congress/](Congress/)
- [AcademyAwards/](AcademyAwards/)

### 16  Design and sample size decisions
- [SampleSize/](SampleSize/)
    - [simulation_tv.md](SampleSize/simulation_tv.md) - Sample size simulation
- [FakeMidtermFinal/](FakeMidtermFinal/)
    - [simulation_based_design_tv.md](FakeMidtermFinal/simulation_based_design_tv.md) - Fake dataset of a randomized experiment on student grades
- [ElectricCompany/](ElectricCompany/)
    - [electric_tv.md](ElectricCompany/electric_tv.md) - Analysis of "Electric Company" data

### 17  Poststratification and missing-data imputation
- [Poststrat/](Poststrat/)
    - [poststrat_tv.md](Poststrat/poststrat_tv.md) - Poststratification after estimation
    - [poststrat2_tv.md](Poststrat/poststrat2_tv.md) - Poststratification after estimation
- [Imputation/](Imputation/)
    - [imputation_tv.md](Imputation/imputation_tv.md) - Regression-based imputation for the Social Indicators Survey

### 18  Causal inference basics and randomized experiments
- [Sesame/](Sesame/)
    - [sesame_tv.md](Sesame/sesame_tv.md) - Causal analysis of Sesame Street experiment

### 19  Causal inference using regression on the treatment variable
- [ElectricCompany/](ElectricCompany/)
    - [electric_tv.md](ElectricCompany/electric_tv.md) - Analysis of "Electric Company" data
- [Incentives/](Incentives/)
    - [incentives_tv.md](Incentives/incentives_tv.md) - Simple analysis of incentives data
- [Cows/](Cows/)

### 20  Observational studies with all confounders assumed to be measured
- [ElectricCompany/](ElectricCompany/)
    - [electric_tv.md](ElectricCompany/electric_tv.md) - Analysis of "Electric Company" data
- [Childcare/](Childcare/)
    - [childcare_tv.md](Childcare/childcare_tv.md) - Infant Health and Development Program (IHDP) example
- [Lalonde/](Lalonde/)

### 21  More advanced topics in causal inference
- [Sesame/](Sesame/)
    - [sesame_tv.md](Sesame/sesame_tv.md) - Causal analysis of Sesame Street experiment
- [ChileSchools/](ChileSchools/)
    - [chile_schools_tv.md](ChileSchools/chile_schools_tv.md) - ChileSchools example.
- [Bypass/](Bypass/)

### 22  Advanced regression and multilevel models
- [Golf/](Golf/)
    - [golf_tv.md](Golf/golf_tv.md) - Gold putting accuracy: Fitting a nonlinear model using Stan
- [Gay/](Gay/)
    - [gay_tv.md](Gay/gay_tv.md) - Nonlinear models (LOESS and spline) and political attitudes as a function of age
- [ElectionsEconomy/](ElectionsEconomy/)
    - [hibbs_tv.md](ElectionsEconomy/hibbs_tv.md) - Predicting presidential vote share from the economy
- [Scalability/](Scalability/)
    - [scalability_tv.md](Scalability/scalability_tv.md) - Demonstrate computation speed with 100,000 observations

### A Computing in R
- [Coins/](Coins/)
- [Mile/](Mile/)
    - [mile_tv.md](Mile/mile_tv.md) - Trend of record times in the mile run
- [Earnings/](Earnings/)
    - [earnings_data_tv.md](Earnings/earnings_data_tv.md) - Read in and prepare earnings data
- [Parabola/](Parabola/)
    - [parabola_tv.md](Parabola/parabola_tv.md) - Demonstration of using Stan for optimization
- [Restaurant/](Restaurant/)
    - [restaurant_tv.md](Restaurant/restaurant_tv.md) - Demonstration of using Stan for optimization
- [DifferentSoftware/](DifferentSoftware/)
    - [linear_tv.md](DifferentSoftware/linear_tv.md) - Linear regression using different software options

-------------

## Examples alphabetically

- [AcademyAwards/](AcademyAwards/)
- [AgePeriodCohort/](AgePeriodCohort/)
    - [births_tv.md](AgePeriodCohort/births_tv.md) - Age adjustment
- [Arsenic/](Arsenic/)
    - [arsenic_logistic_building_tv.md](Arsenic/arsenic_logistic_building_tv.md) - Building a logistic regression model: wells in Bangladesh
    - [arsenic_logistic_apc_tv.md](Arsenic/arsenic_logistic_apc_tv.md) - Average predictive comparisons for a logistic regression model: wells in Bangladesh
    - [arsenic_logistic_residuals_tv.md](Arsenic/arsenic_logistic_residuals_tv.md) - Residual plots for a logistic regression model: wells in Bangladesh
- [Beauty/](Beauty/)
    - [beauty_tv.md](Beauty/beauty_tv.md) - Student evaluations of instructors’ beauty and teaching quality
- [Bypass/](Bypass/)
- [CentralLimitTheorem/](CentralLimitTheorem/)
    - [heightweight_tv.md](CentralLimitTheorem/heightweight_tv.md) - Illustrate central limit theorem and normal distribution
- [Childcare/](Childcare/)
    - [childcare_tv.md](Childcare/childcare_tv.md) - Infant Health and Development Program (IHDP) example
- [ChileSchools/](ChileSchools/)
    - [chile_schools_tv.md](ChileSchools/chile_schools_tv.md) - ChileSchools example.
- [Coins/](Coins/)
- [Congress/](Congress/)
    - [congress_tv.md](Congress/congress_tv.md) - Predictive uncertainty for congressional elections
    - [congress_plots_tv.md](Congress/congress_plots_tv.md) - Predictive uncertainty for congressional elections
- [Coop/](Coop/)
    - [riverbay_tv.md](Coop/riverbay_tv.md) - Example of hypothesis testing
- [Coverage/](Coverage/)
    - [coverage_tv.md](Coverage/coverage_tv.md) - Example of coverage
- [Cows/](Cows/)
- [CrossValidation/](CrossValidation/)
    - [crossvalidation_tv.md](CrossValidation/crossvalidation_tv.md) - Demonstration of cross validation
- [Death/](Death/)
    - [polls_tv.md](Death/polls_tv.md) - Proportion of American adults supporting the death penalty
- [DifferentSoftware/](DifferentSoftware/)
    - [linear_tv.md](DifferentSoftware/linear_tv.md) - Linear regression using different software options
- [Earnings/](Earnings/)
    - [earnings_bootstrap_tv.md](Earnings/earnings_bootstrap_tv.md) - Bootstrapping to simulate the sampling distribution
    - [earnings_compound_tv.md](Earnings/earnings_compound_tv.md) - Compound discrete-continuous model
    - [earnings_regression_tv.md](Earnings/earnings_regression_tv.md) - Predict respondents' yearly earnings using survey data from 1990
    - [height_and_weight_tv.md](Earnings/height_and_weight_tv.md) - Predict weight
    - [earnings_data_tv.md](Earnings/earnings_data_tv.md) - Read in and prepare earnings data
- [ElectionsEconomy/](ElectionsEconomy/)
    - [bayes_tv.md](ElectionsEconomy/bayes_tv.md) - Demonstration of Bayesian information aggregation
    - [hibbs_coverage_tv.md](ElectionsEconomy/hibbs_coverage_tv.md) - Checking the model-fitting procedure using fake-data simulation.
    - [hibbs_tv.md](ElectionsEconomy/hibbs_tv.md) - Predicting presidential vote share from the economy
    - [hills_tv.md](ElectionsEconomy/hills_tv.md) - Present uncertainty in parameter estimates
- [ElectricCompany/](ElectricCompany/)
    - [electric_tv.md](ElectricCompany/electric_tv.md) - Analysis of "Electric Company" data
- [FakeKCV/](FakeKCV/)
    - [fake_kcv_tv.md](FakeKCV/fake_kcv_tv.md) - Demonstration of $K$-fold cross-validation using simulated data
- [FakeMidtermFinal/](FakeMidtermFinal/)
    - [simulation_tv.md](FakeMidtermFinal/simulation_tv.md) - Fake dataset of 1,000 students' scores on a midterm and final exam
    - [simulation_based_design_tv.md](FakeMidtermFinal/simulation_based_design_tv.md) - Fake dataset of a randomized experiment on student grades
- [Gay/](Gay/)
    - [gay_simple_tv.md](Gay/gay_simple_tv.md) - Simple models (linear and discretized age) and political attitudes as a function of age
    - [gay_tv.md](Gay/gay_tv.md) - Nonlinear models (LOESS and spline) and political attitudes as a function of age
- [Girls/](Girls/)
- [Golf/](Golf/)
    - [golf_tv.md](Golf/golf_tv.md) - Gold putting accuracy: Fitting a nonlinear model using Stan
- [HDI/](HDI/)
    - [hdi_tv.md](HDI/hdi_tv.md) - Human Development Index - Looking at data in different ways
- [HealthExpenditure/](HealthExpenditure/)
    - [healthexpenditure_tv.md](HealthExpenditure/healthexpenditure_tv.md) - Discovery through graphs of data and models
- [Helicopters/](Helicopters/)
    - [helicopters_tv.md](Helicopters/helicopters_tv.md) - Example data file for helicopter flying time exercise
- [Imputation/](Imputation/)
    - [imputation_tv.md](Imputation/imputation_tv.md) - Regression-based imputation for the Social Indicators Survey
- [Incentives/](Incentives/)
    - [incentives_tv.md](Incentives/incentives_tv.md) - Simple analysis of incentives data
- [Influence/](Influence/)
    - [influence_tv.md](Influence/influence_tv.md) - Influence of individual points in a fitted regression
- [Introclass/](Introclass/)
    - [residual_plots_tv.md](Introclass/residual_plots_tv.md) - Plot residuals vs.\ predicted values, or residuals vs.\ observed values?
- [KidIQ/](KidIQ/)
    - [kidiq_tv.md](KidIQ/kidiq_tv.md) - Linear regression with multiple predictors
- [Lalonde/](Lalonde/)
- [LogisticPriors/](LogisticPriors/)
    - [logistic_priors_tv.md](LogisticPriors/logistic_priors_tv.md) - Effect of priors in logistic regression
- [LogitGraphs/](LogitGraphs/)
    - [logitgraphs_tv.md](LogitGraphs/logitgraphs_tv.md) - Different ways of displaying logistic regression
- [Mesquite/](Mesquite/)
    - [mesquite_tv.md](Mesquite/mesquite_tv.md) - Predicting the yields of mesquite bushes
- [Metabolic/](Metabolic/)
    - [metabolic_tv.md](Metabolic/metabolic_tv.md) - How to interpret a power law or log-log regression
- [Mile/](Mile/)
    - [mile_tv.md](Mile/mile_tv.md) - Trend of record times in the mile run
- [Names/](Names/)
    - [lastletters_tv.md](Names/lastletters_tv.md) - Last letters - Distributions of last letters of names of American babies
- [NES/](NES/)
    - [nes_linear_tv.md](NES/nes_linear_tv.md) - Fitting the same regression to many datasets
    - [nes_logistic_tv.md](NES/nes_logistic_tv.md) - Logistic regression, identifiability, and separation
- [Newcomb/](Newcomb/)
    - [newcomb_tv.md](Newcomb/newcomb_tv.md) - Posterior predictive checking of Normal model for Newcomb's speed of light data
- [Parabola/](Parabola/)
    - [parabola_tv.md](Parabola/parabola_tv.md) - Demonstration of using Stan for optimization
- [Peacekeeping/](Peacekeeping/)
    - [peace_tv.md](Peacekeeping/peace_tv.md) - Outcomes after civil war in countries with and without United Nations peacekeeping
- [PearsonLee/](PearsonLee/)
    - [heights_tv.md](PearsonLee/heights_tv.md) - The heredity of height. Published in 1903 by Karl Pearson and Alice Lee.
- [Pew/](Pew/)
    - [pew_tv.md](Pew/pew_tv.md) - Miscellaneous analyses using raw Pew data
- [PoissonExample/](PoissonExample/)
    - [poisson_regression_tv.md](PoissonExample/poisson_regression_tv.md) - Demonstrate Poisson regression with simulated data
- [Pollution/](Pollution/)
    - [pollution_tv.md](Pollution/pollution_tv.md) - Pollution data
- [Poststrat/](Poststrat/)
    - [poststrat_tv.md](Poststrat/poststrat_tv.md) - Poststratification after estimation
    - [poststrat2_tv.md](Poststrat/poststrat2_tv.md) - Poststratification after estimation
- [ProbabilitySimulation/](ProbabilitySimulation/)
    - [probsim_tv.md](ProbabilitySimulation/probsim_tv.md) - Simulation of probability models
- [Pyth/](Pyth/)
- [Residuals/](Residuals/)
    - [residuals_tv.md](Residuals/residuals_tv.md) - Plotting the data and fitted model
- [Restaurant/](Restaurant/)
    - [restaurant_tv.md](Restaurant/restaurant_tv.md) - Demonstration of using Stan for optimization
- [RiskyBehavior/](RiskyBehavior/)
    - [risky_tv.md](RiskyBehavior/risky_tv.md) Risky behavior data
- [Roaches/](Roaches/)
    - [roaches_tv.md](Roaches/roaches_tv.md) - Analyze the effect of integrated pest management on reducing cockroach levels in urban apartments
- [Robit/](Robit/)
    - [robit_tv.md](Robit/robit_tv.md) - Comparison of robit and logit models for binary data
- [Rodents/](Rodents/)
- [Rsquared/](Rsquared/)
    - [rsquared_tv.md](Rsquared/rsquared_tv.md) - Bayesian R^2
- [SampleSize/](SampleSize/)
    - [simulation_tv.md](SampleSize/simulation_tv.md) - Sample size simulation
- [Scalability/](Scalability/)
    - [scalability_tv.md](Scalability/scalability_tv.md) - Demonstrate computation speed with 100,000 observations
- [Sesame/](Sesame/)
    - [sesame_tv.md](Sesame/sesame_tv.md) - Causal analysis of Sesame Street experiment
- [SexRatio/](SexRatio/)
    - [sexratio_tv.md](SexRatio/sexratio_tv.md) - Example where an informative prior makes a difference
- [SimpleCausal/](SimpleCausal/)
    - [causal_tv.md](SimpleCausal/causal_tv.md) - Simple graphs illustrating regression for causal inference
- [Simplest/](Simplest/)
    - [simplest_tv.md](Simplest/simplest_tv.md) - Linear regression with a single predictor
- [Stents/](Stents/)
    - [stents_tv.md](Stents/stents_tv.md) - Stents - comparing distributions
- [Storable/](Storable/)
    - [storable_tv.md](Storable/storable_tv.md) - Ordered categorical data analysis with a study from experimental economics, on the topic of "storable votes"
- [Student/](Student/)
    - [student_tv.md](Student/student_tv.md) - Models for regression coefficients
- [Unemployment/](Unemployment/)
    - [unemployment_tv.md](Unemployment/unemployment_tv.md) - Time series fit and posterior predictive model checking for unemployment series

